export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const TIP_TOGGLE = 'TIP_TOGGLE';
export const LOGIN_TOGGLE = 'LOGIN_TOGGLE';
